server:
  port: 8081

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: FULL

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
